### ISSUE TITLE
[Review] 请保留原项目的 commit 历史

### ISSUE THREAD

**Issue by ExerciseBook** [kater-team/formatting-extend#1]
这种不保留 commit 历史的项目分支会造成如下问题

1. 不易审查本插件的改动
2. 不易跟随插件主分支更新

https://github.com/kater-team/gamification-extend
https://github.com/kater-team/ignore-users-extend

其余两个插件均有类似问题可以尝试的解决方案

1. `git clone` 原项目
2. 将本仓库的内容覆盖到步骤 1 克隆的项目
3. 将 2 的步骤 commit
4. `git push -f` 到本仓库

如果不会操作的话可以进一步讨论。

**Comment by Hehongyuanlove** [comment]
formatting 属于简单项目 
[gamification-extend](https://github.com/kater-team/gamification-extend) 已经补充 commit
[ignore-users-extend](https://github.com/kater-team/ignore-users-extend) 还在商议 不在本次审查范围

**Comment by ExerciseBook** [comment]
抱歉抱歉，是我的锅。
我还以为是某些插件的 fork 没想到是私有插件。
